:toc:

= jqassistant-asciidoctorj-extension

The `jqassistant-asciidoctorj-extension` is an asciidoctor extension that offers a convenient way of creating a jQAssistant report inside the asciidoctor pipeline.
The plugin is using the https://docs.asciidoctor.org/asciidoctorj/latest/extensions/extensions-introduction/[asciidoctor extension api] to hook into the https://asciidoctor.org/[asciidoctor] pipeline.

You can use it to convert your jqassistant-report.xml (jQAssistant generates this for you) directly to html, pdf, ePub and others, as long as there's an Asciidoctor converter for it.

== Using the jqassistant-asciidoctorj-extension

As an example of how to use the plugin, you can take a look at the following maven plugin configuration for the `asciidoctor-maven-plugin`.

[source, xml]
----
<!-- Define the following inside the build part of your pom.xml -->

<plugins>
    <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>3.1.1</version>
        <configuration>
            <attributes>
                <jqassistant-report-path>
                    ${project.build.directory}/jqassistant/jqassistant-report.xml <!--1-->
                </jqassistant-report-path>
                <jqassistant-templates-path>
                    your-custom-template-jar-or-folder-name <!--2-->
                </jqassistant-templates-path>
                <imagesDir>
                    your-desired-folder-to-store-pictures-inside-your-output-directory <!--3-->
                </imagesDir>
            </attributes>
        </configuration>
        <executions>
            <execution>
                <id>output-html</id>
                <phase>verify</phase>
                <goals>
                    <goal>process-asciidoc</goal>
                </goals>
            </execution>
        </executions>
        <dependencies>
            <dependency>
                <groupId>org.jqassistant.tooling.asciidoctorj</groupId>
                <artifactId>jqassistant-asciidoctorj-extensions</artifactId>
                <version>1.1.0</version> <!--4-->
            </dependency>
        </dependencies>
    </plugin>
</plugins>
----
<1> place the path to your jqassistant-report.xml here. Check <<Finding your jqassistant-report.xml>> for information.
<2> OPTIONAL: If not declared, the extension will use the default templates. If you want to use your templates, place the name of your custom templates location here.
<3> OPTIONAL: If you add this option, the extension will copy all pictures (f.e. diagrams) generated by jQAssistant into the defined folder. The folder will be created by asciidoctor relative to the generated docs folder.
<4> place your desired version of the extension here. Check https://mvnrepository.com/artifact/org.jqassistant.tooling.asciidoctorj/jqassistant-asciidoctorj-extensions[maven repository] for the newest version.

== Create your report

In general, there are two possible macros (called includes) you can use with the `jqassistant-asciidoctorj-extension`.

1. `include::jQAssistant:Summary[]` will give you a summary table of all constraints and concepts with their id, description, severity and status. They're sorted by Status and id name.
2. `include::jQAssistant:Rules[]` will give you a detailed list of all constraints and concepts with additional information like result tables or graphs

For both of them, you have the option to assign three additional attributes:

* concepts
* constraints
* status

For attributes _concepts_ and _constraints_, you can assign an id or id wildcard to either of them. In this case, you get back some specific jQAssisstant concepts and constraints. This could look like this:

* `include::jQAssistant:Summary[concepts="jQA:my:specific:concept-id"]` would result in a summary table that only contains the concept with the name jQA:my:specific:concept-id (if it exists). Constraints are not rendered in this case.

* `include::jQAssistant:Summary[concepts="jQA:my:specific:concept-id", constraints="*"]` would result in a summary table containing the concept with the name jQA:my:specific:concept-id. Also, all constraints will be displayed.

* `include::jQAssistant:Rules[constraints="jQA:a*", concepts="jQA:my:specific:concept-id"]` would result in a list containing all constraints with their details that start with "jQA:a". Also, it will contain exactly one concept (if it exists) with the id "jQA:my:specific:concept-id" (this concept will also be displayed with its details).

The attribute _status_ allows you to filter the rendered jQAssistant constraints based on their execution results. It accepts any combination of "SUCCESS", "SKIPPED", "WARNING", and "FAILURE", defaulting to "WARNING, FAILURE" if omitted. Note that the "*" wildcard is not supported. This could look like this:

* `include::jQAssistant:Summary[constraints="*", status="WARNING, FAILURE"]` would result in a summary table containing all constraints that triggered warnings or failures during the analysis.

* `include::jQAssistant: Rules[concepts="*", status="WARNING, FAILURE"]` would result in a list containing the all concepts that triggered warnings or failures, providing detailed information about the issue.

NOTE: Normally `include::...` 's are used to reference and display other files inside the adoc file they're written in. However, in our case these `include::...` 's are replaced by the `jqassistant-asciidoctor-extension`.

NOTE: The standard behaviour of the default templates is to render Rule-Ids in the `include::jQAssistant:Rules[]` with level 0 headings (adoc notation: `=`). If you want to change that, you may use the leveloffset attribute. F.e. `include::jQAssistant:Rules[leveloffset=+1]`: This would yield an output with all Rule-Ids having a level 1 heading instead of level 0 (adoc notation: `=` -> `==`).

== Finding your jqassistant-report.xml

Normally you can refer to your jqassistant-report.xml via `${project.build.directory}/jqassistant/jqassistant-report.xml`. You can check the exact location by searching for `jqassistant-report.xml` in your jQA output directory (this xml is created by jQA at runtime).


