= Apply Component Dependencies

== Status

Accepted

== Context

The CWA server consists of common and service components and defined dependencies between them.

For maintenance reasons these must be actively managed and monitored to prevent erosion.

== Decision

The following dependencies between components are defined:

[[adr:ComponentDependencyDefinition]]
[plantuml,componentDependencyDefinition,role=concept,requiresConcepts="adr:CommonComponent,adr:ServiceComponent"]
.The defined dependencies between components are represented by `DEFINES_DEPENDENCY` relations.
----
@startuml
skinparam componentStyle uml2

folder "Common" {
  [{name:"shared"}]       as shared       <<Common>><<Component>><<Artifact>>
  [{name:"persistence"}]  as persistence  <<Common>><<Component>><<Artifact>>
  [{name:"protocols"}]    as protocols    <<Common>><<Component>><<Artifact>>
  [{name:"federation"}]   as federation   <<Common>><<Component>><<Artifact>>
}

folder "Service" {
  [(any)]                 as service      <<Service>><<Component>><<Artifact>>
}

persistence   --> shared        : (+):DEFINES_DEPENDENCY
persistence   --> protocols     : (+):DEFINES_DEPENDENCY
federation    --> protocols     : (+):DEFINES_DEPENDENCY

service       --> shared        : (+):DEFINES_DEPENDENCY
service       --> persistence   : (+):DEFINES_DEPENDENCY
service       --> protocols     : (+):DEFINES_DEPENDENCY
service       --> federation    : (+):DEFINES_DEPENDENCY

@enduml
----
// NOTE: The defined dependencies can as well be expressed using Cypher

== Consequences

[[adr:ComponentDependency]]
[source,cypher,role=concept,requiresConcepts="adr:ComponentDependencyDefinition",reportType="csv"]
.A dependency between two components exists if there are dependencies between contained Java types.
----
MATCH
  (c1:Component:Artifact)-[:CONTAINS]->(t1:Type),
  (c2:Component:Artifact)-[:CONTAINS]->(t2:Type),
  (t1)-[dependsOn:DEPENDS_ON]->(t2)
WHERE
  c1 <> c2
WITH
  c1, c2, count(dependsOn) as weight
MERGE
  (c1)-[dependsOnComponent:DEPENDS_ON_COMPONENT]->(c2)
SET
  dependsOnComponent.weight = weight
RETURN
  c1.name as Dependent, c2.name as Dependency, dependsOnComponent.weight as Weight
ORDER BY
  Weight desc
----

[[adr:UndefinedComponentDependency]]
[source,cypher,role=constraint,requiresConcepts="adr:ComponentDependencyDefinition,adr:ComponentDependency"]
.There must be no undefined dependency between components.
----
MATCH
  (c1:Component:Artifact)-[:DEPENDS_ON_COMPONENT]->(c2:Component:Artifact)
WHERE NOT
  (c1)-[:DEFINES_DEPENDENCY]->(c2)
WITH
  c1, c2
MATCH
  (c1)-[:CONTAINS]->(t1:Type),
  (c2)-[:CONTAINS]->(t2:Type),
  (t1)-[dependsOn:DEPENDS_ON]->(t2)
RETURN
  c1 as Dependent, c2 as InvalidDependency, t1 as DependentType, t2 as DependencyType, dependsOn.weight as Weight
----

== Reports

[[adr:ComponentDependencyPlantUMLReport]]
[source,cypher,role=concept,requiresConcepts="adr:ComponentDependency" reportType="plantuml-component-diagram"]
.Component dependencies as PlantUML component diagram
----
MATCH
  (c1:Component:Artifact)-[dependsOnComponent:DEPENDS_ON_COMPONENT]->(c2:Component:Artifact)
RETURN
  c1 AS Dependent, dependsOnComponent AS DependsOnComponent, c2 AS Dependency
----

[[adr:ComponentDependencyGraphMLReport]]
[source,cypher,role=concept,requiresConcepts="adr:ComponentDependency",reportType="graphml"]
.Component dependencies as GraphML file.
----
MATCH
  (c1:Component:Artifact)-[dependsOnComponent:DEPENDS_ON_COMPONENT]->(c2:Component:Artifact)
RETURN
  c1 AS Dependent, dependsOnComponent AS DependsOnComponent, c2 AS Dependency
----
